[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_weather = "D3tskW3Hk82eLGcpWZwetbiw6uNChdrPBw4xi6yFmZgW"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
